# Generated by Django 4.2.2 on 2023-06-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=150)),
                ('lancamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('tel_para_contato', models.IntegerField(null=True)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='livraria_app.livro')),
            ],
        ),
    ]
