# Generated by Django 4.2.1 on 2023-05-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
