# Generated by Django 4.2.1 on 2023-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cidade',
            field=models.CharField(max_length=20),
        ),
    ]
